name = "OptRNN"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Alireza Miraliakbar"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
